create_clock -period 8.000 -name clock125 -waveform {0.000 4.000} [get_ports clock]



set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {atan2Out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports valid]



set_operating_conditions -grade commercial
